### ISSUE TITLE
Модуль Retail Rocet 2 урок 

### ISSUE THREAD

**Issue by vycheslavol** [dani32iz/public_addons_for_cscart#1]
Добрый день.
В обновленной версии движка 4.3.1 решил поставить данный модуль, но после того как все вашей инструкции все сделал (2 урок) и установил модуль, то сразу вышла ошибка (ОшибкаPO-файл содержит синтаксические ошибки или имеет некорректную структуру. Пожалуйста, проверьте его и повторите попытку еще раз.)
И скрипт не виден на сайте, и так же не виден в кабинете Retail Rocet.
Сайт на который ставлю www.101kubik.ru
Сейчас модуль включен.
Подскажете что может быть?

**Comment by dani32iz** [comment]
@vycheslavol 
В .po файле (он добавляет переводы) , добавьте две пустые строки в конец файла

**Comment by dani32iz** [comment]
Залил измененный модуль в папку 4.3.x 

Установка проходит, остальное не проверял.

https://github.com/dani32iz/public_addons_for_cscart/tree/master/4.3.x/retailrocket

**Comment by vycheslavol** [comment]
Все добавил, ошибки не выдало.
Спасибо.

После того как сделал урок 3, установка основного кода. Не работает.

**Comment by dani32iz** [comment]
Проверяйте, я же рассказываю что происходит, сам смогу проверить только завтра.

**Comment by vycheslavol** [comment]
Я прочитал тему и на форуме и все перепроверил. Не работает. На форуме вы говорили о rees46, загрузил их модуль все работает.
Но выяснилось вот еще после обновления перестал работать модуль яндексметрика, счетчик прописан (номер) на самом сайте, но сам счетчик в метрике говорит, что его нет.
После того как поставил  отдельный блок и прописал там скрип яндексметрики, то показало что счетчик обнаружен.
Может еще из-за этого не работает модуль РР? Ну и естественно сам яндексметрика.
Думаю завтра обратиться в техподдержку

**Comment by dani32iz** [comment]
Версия какая?

**Comment by vycheslavol** [comment]
4.3.1
В ночь поставлю 4.3.2 и посмотрю как будет, а то сейчас реклама работает

**Comment by vycheslavol** [comment]
но в обновлении 4.3.2 не увидел, чтобы делались обновления в яндекс метрике(

**Comment by dani32iz** [comment]
Обновляйте до 4.3.2, так как в 4.3.1 была проблема которая вырезала Метрику и другие скрипты.

**Comment by vycheslavol** [comment]
Понял, спс

**Comment by dani32iz** [comment]
Вот фикс
http://forum.cs-cart.com/topic/40198-%d0%ba%d1%82%d0%be-%d0%bd%d0%b8%d0%b1%d1%83%d0%b4%d1%8c-%d0%be%d0%b1%d0%bd%d0%be%d0%b2%d0%b8%d0%bb%d1%81%d1%8f-%d0%bd%d0%b0-431/page__view__findpost__p__216146

**Comment by vycheslavol** [comment]
Обновил, все работает. Спасибо за помощь

**Comment by dani32iz** [comment]
Отлично.
